import { GetServerSideProps } from "next";
import nookies from "nookies";
import Head from "next/head";
import Link from "next/link";
import styles from "@/styles/Home.module.css";
import { fetchRefreshedAccessToken } from "@/utils/api";
import { isRefreshedAccessTokenObject } from "@/types/typeGuards";

interface HomePageProps {
  existRefreshTokenCookie: boolean;
}

export const getServerSideProps: GetServerSideProps<HomePageProps> = async (
  ctx
) => {
  nookies.destroy(ctx, "refreshToken");
  return {
    props: {
      existRefreshTokenCookie: nookies.get(ctx).refreshToken !== undefined,
    },
  };
};

const Home = () => {
  return (
    <div className={styles.Home}>
      <Head>
        <title>Lyrics Visualizer Beta</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <h1 className={styles.pageTitle}>Lyrics Visualizer Beta</h1>
        <div className={styles.links}>
          <Link className={styles.connectLink} href="/api/spotify/login">
            Connect to Spotify
          </Link>
        </div>
      </div>
    </div>
  );
};

export default Home;
